services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
      # Add your API keys here:
      - key: OPENAI_API_KEY
        value: your_openai_key
      - key: ANTHROPIC_API_KEY
        value: your_anthropic_key
      - key: GEMINI_API_KEY
        value: your_gemini_key
      - key: GROQ_API_KEY
        value: your_groq_key

  - type: web
    name: frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    staticPath: /frontend/build
